const messages = {
    loginSuccess: 'Login successful.',
    signupSuccess: 'Signup successful.',
    invalidUser: 'Invalid email or password.',
    userAlreadyExists: 'User already exists.',
    otpSentSuccess: 'OTP sent successfully.',
    otpVerifiedSuccess: 'OTP verified successfully.',
    otpNotFound: 'OTP not found.',
    otpExpired: 'OTP has expired.',
    invalidOtp: 'Invalid OTP.',
    employeeNotFound: 'Employee not found.',
    loginSuccess: 'Login successful.',
    signupSuccess: 'Signup successful.',
    invalidUser: 'Invalid user credentials.',
    invalidOTP: 'Invalid OTP.',
    maxAttemptsReached: 'Maximum OTP attempts reached. Please try again later.',
    emailNotFound: 'Email not found.',
    passwordMismatch: 'New passwords do not match.',
    passwordUpdated: 'Password updated successfully.',
    otpVerificationFailed: 'OTP verification failed.',
    maximumAttempted: 'Maximum OTP resend attempts reached.',
    loginSuccess: 'Login successful',
    signupSuccess: 'Signup successful',
    otpGenerationSuccess: 'OTP sent successfully',
    otpVerificationSuccess: 'OTP verified successfully',
    passwordResetSuccess: 'Password reset successful',

    // Error messages
    invalidUser: 'Invalid User',
    invalidOTP: 'Invalid OTP',
    otpVerificationFailed: 'OTP verification failed',
    passwordMismatch: 'New passwords do not match',
    userNotFound: 'User not found',
    maximumAttemptsReached: 'Maximum attempts reached. Please try again later.',
    emailNotValid: 'This email is not valid',
    otpGenerationFailed: 'OTP generation failed',
    passwordUpdateFailed: 'Password update failed',
    loginSuccess: 'Login successful.',
    invalidEmail: 'Invalid email address. Please register first.',
    incorrectPassword: 'Incorrect password. Please try again.',
    unexpectedError: 'An unexpected error occurred. Please try again.',
    emailRequired: 'Please enter a registered email address.',
    passwordRequired: 'Incorrect password. Please try again.',
    OTP_GENERATION_SUCCESS: 'OTP sent successfully! Please check your email.',
    INVALID_EMAIL: 'This email is not valid.',
    MAX_ATTEMPTS_REACHED: 'Maximum attempts reached. Please try again later.',
    OTP_ERROR: 'An error occurred while generating OTP.',
    emailnotRegister: 'Please enter a registered email ID.',
    emailRequired:'Email required',
    otpRequired:'Otp Required',
    invalidEmailFormat:'Invalid Email Format',
    invalidOtpFormat:'Invalid OTP Format',
    signupSuccess: "User registered successfully.",
    passwordRequired: "Password is required.",
    addressRequired: "Address is required.",
    userAlreadyExists: "User already exists.",
    internalError: "An error occurred during signup, please try again later.",
    invalidCredentials: "Invalid credentials, please try again.",
    nameisrequired:"Name is Required",
    invalidMobile:"Invalid Mobile",
    emailpasswordRequired:'Email and password are required',
    emailAlreadyRegistered:"This email id is already register Please enter a new email id",
    confirmPasswordRequired:"Confirm Password Required",
    registerplz:'Invalid email address. Please register first.',
    logoutSuccess:'Logout Sucessfully',
    invalidTokenFormat:'Invalid Token Format',
    createdSucess:'Employee Create sucessfully',
    deactivated:'Employee deactivated Sucessfully',
    activated:'Employee activated Sucessfully',
     GOOGLE_SIGNUP_SUCCESS_MSG :'User successfully registered.',
     GOOGLE_SIGNUP_FAIL_MSG :'User already exists. Please log in instead.',
     GOOGLE_SIGNUP_ERROR_MSG :'Internal Server Error',
     GOOGLE_MISSING_CODE_MSG :'No code provided',
     GOOGLE_ACCESS_TOKEN_FAIL_MSG :'Failed to get valid access token from Google'
};

module.exports = messages;

// constants/messages.js
const MESSAGES = {
    SUCCESS: {
      FETCH_SUCCESS: "Data fetched successfully.",
      CREATED_SUCCESS: "Data created successfully.",
      UPDATED_SUCCESS: "Data updated successfully.",
      DELETED_SUCCESS: "Data deleted successfully.",
    },
    ERROR: {
      INTERNAL_SERVER_ERROR: "Internal server error occurred.",
      NOT_FOUND: "The requested resource was not found.",
      UNAUTHORIZED: "You are not authorized to perform this action.",
      BAD_REQUEST: "Invalid request parameters.",
    },
    USER: {
      ACTIVE: "Login Successfully.",
      INACTIVE: "User is not active. Please contact the administrator.",
      NOT_FOUND: "User not found. Please register.",
    },
  };
  
  module.exports = MESSAGES;
